apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-config
data:
  haproxy.cfg: |
    resolvers kubedns
      nameserver dns1 10.96.0.10:53
      resolve_retries 10
      timeout retry   10s
      hold valid      10s

    global
      log stdout local0
      maxconn 50000
      debug

    defaults
      log global
      maxconn 3000
      mode http
      timeout connect 10s
      timeout client 30s
      timeout server 30s
      option httplog
      option logasap
      option http-use-htx

    frontend fe_proxy
      bind :50051 proto h2
      default_backend be_servers

    backend be_servers
      balance roundrobin
      server server1 helloworld-server.default.svc.cluster.local:50051 check maxconn 20 proto h2
      #server server1 helloworld-server.default.svc.cluster.local:50051 check resolvers kubedns check maxconn 20 alpn h2
      #server server1 helloworld-server.default.svc.cluster.local:50051 check maxconn 20 alpn h2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: haproxy
  labels:
    app: haproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: haproxy
  template:
    metadata:
      labels:
        app: haproxy
    spec:
      volumes:
      - name: haproxy-config-volume
        configMap:
          name: haproxy-config            
      containers:
      - name: server
        image: haproxy
        imagePullPolicy: Never
        ports:
        - containerPort: 50051
        resources:
          limits:
            memory: "1Gi"
            cpu: 1
          requests:
            memory: "50Mi"
            cpu: "100m"
        volumeMounts:
        - name: haproxy-config-volume
          mountPath: /usr/local/etc/haproxy/
---
apiVersion: v1
kind: Service
metadata:
  name: haproxy
spec:
  #type: ClusterIP
  #clusterIP: None
  selector:
    app: haproxy
  ports:
  - protocol: TCP
    port: 50051
    targetPort: 50051
    