apiVersion: v1
kind: ConfigMap
metadata:
  name: grpc-config
data:
  grpc.conf: |
    upstream grpcservers {
        server helloworld-grpc-server:50051;
    }
    server {
      listen 50051 http2;
      resolver 8.8.8.8;
        location / {
          grpc_pass grpc://grpcservers;
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
      - name: grpc-config-volume
        configMap:
          name: grpc-config
      containers:
      - name: server
        image: nginx
        ports:
        - containerPort: 50051
        resources:
          limits:
            memory: "1Gi"
            cpu: 1
          requests:
            memory: "50Mi"
            cpu: "100m"
        volumeMounts:
        - name: grpc-config-volume
          mountPath: /etc/nginx/conf.d/

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 50051
    targetPort: 50051
    