apiVersion: v1
kind: Service
metadata:
  name: helloworld-grpc-server
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: helloworld-grpc-server
  ports:
  - protocol: TCP
    port: 50051
    targetPort: 50051
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-grpc-server
  labels:
    app: helloworld-grpc-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: helloworld-grpc-server
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: helloworld-grpc-server
    spec:
      containers:
      - name: server
        image: fkarakas/helloworld-grpc:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 50051
        resources:
          limits:
            memory: "1Gi"
            cpu: 1
          requests:
            memory: "50Mi"
            cpu: "100m"
        env:
        - name: MODE
          value: "server"
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP

---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-grpc-server
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: helloworld-grpc-server
  ports:
  - protocol: TCP
    port: 50051
    targetPort: 50051
