apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-grpc-client
  labels:
    app: helloworld-grpc-client
spec:  
  replicas: 1
  selector:
    matchLabels:
      app: helloworld-grpc-client
  template:
    metadata:
      annotations:
        linkerd.io/inject: disabled
      labels:
        app: helloworld-grpc-client
    spec:      
      serviceAccountName: endpoints-reader-sa
      #automountServiceAccountToken: true
      containers:
      - name: client
        image: fkarakas/helloworld-grpc:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "1Gi"
            cpu: 1
          requests:
            memory: "50Mi"
            cpu: "100m"
        env:
        - name: MODE
          value: "client"
        - name: LB
          value: "kube"
        - name: SERVER
          value: "helloworld-grpc-server.default:50051"
          #value: "haproxy:50051"
          #value: "nginx:50051"
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: endpoints-reader-role
  namespace: default
rules:
- apiGroups: [""]
  resources:
  - namespaces
  - endpoints
  - services
  - nodes
  - pods
  verbs:
  - get
  - watch
  - list
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: endpoints-reader-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name:  endpoints-reader-rb
  namespace: default
subjects:
- kind: ServiceAccount
  name: endpoints-reader-sa
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: endpoints-reader-role
  

