apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-grpc-client
  labels:
    app: helloworld-grpc-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld-grpc-client
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: helloworld-grpc-client
    spec:
      containers:
      - name: client
        image: fkarakas/helloworld-grpc:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "1Gi"
            cpu: 1
          requests:
            memory: "50Mi"
            cpu: "100m"
        env:
        - name: MODE
          value: "client"
        - name: SERVER
          value: "helloworld-grpc-server:50051"
          #value: "haproxy:50051"
          #value: "nginx:50051"
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
